### ISSUE TITLE
Test recommendation on CiteULike dataset

### ISSUE THREAD

**Issue by daniel-acuna** [titipata/science_concierge#2]
Following similar testing procedure as the one described [here](https://www.cs.princeton.edu/~blei/papers/WangBlei2011.pdf). The CiteULike dataset is available [here](http://www.citeulike.org/faq/data.adp)

**Comment by titipata** [comment]
I registered for CiteULike. However, when I tried to go to download pages, I cannot use my username/password to download the data

**Comment by titipata** [comment]
I see. We need to send email to `support13@citeulike.org`
- your name
- your citeulike username
- the institution you are affiliated to
- your research interest in the data
- your email as registered with CiteULike

**Comment by daniel-acuna** [comment]
Lets do it then.

**Comment by titipata** [comment]
We don't test on CiteULike dataset anymore since we use SfN dataset as our core dataset
