### ISSUE TITLE
Documentation ready for Sphinx

### ISSUE THREAD

**Issue by daniel-acuna** [titipata/science_concierge#5]
According to [PLOS CB software submission guidelines](http://journals.plos.org/ploscompbiol/s/submission-guidelines#loc-software-submissions), the following must be met:

> Documentation. This must include instructions for building and installing the software from source, and any dependencies on both proprietary and freely available prerequisites. For software libraries, instructions for using the API are also required.

**Comment by titipata** [comment]
I will work on Wiki page and `gh-page` instead.
